server:
  port: 8090

spring:
  application:
    name: flash-sale-service

  datasource:
    url: jdbc:mysql://localhost:3306/flash_sales
    username: root
    password: rootpassword

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: flash-sale-service.v1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

services:
  timeout: 5s
  inventory:
    base-url: http://inventory-service/api/v1
  product:
    base-url: http://product-service/api/v1

common:
  user-context:
    required: true
