server:
  port: 8083

spring:
  application:
    name: auth_service

keycloak:
  serverUrl: http://localhost:8086
  clientId: ecom
  clientSecret: EQ4Dz6eAOMO5xBsn9aJliSle1c7AJBMQVP2V9i1d8I0sNzGmJoIx99SVm8ULVpZLfH81t967cvsBp3cmvx7BY6
  realm: ecom-realm
