server:
  port: 8083

spring:
  application:
    name: auth-service

keycloak:
  serverUrl: http://localhost:8086
  clientId: ecom
  clientSecret: 7onfGObqcHkZJVFKeSQYuHbH5rUmj4MsFrAMBAbH4gw9lkBem9fFilZTJGiwmP0BwVZjhs9nWSr8LdNVARw5ND
  realm: ecom-realm

services:
  keycloak:
    base-url: http://localhost:8086
    timeout: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
