server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: rootpassword

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: product-service.v1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

  jpa:
    hibernate:
      ddl-auto: update
