server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: rootpassword

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

services:
  product:
    base-url: http://localhost:8080/api/v1
    timeout: 5s
