services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    restart: always
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - ecom-net

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   restart: always
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - broker
  #   networks:
  #     - ecom-net

  redis-server:
    image: redis:8.4-alpine
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecom-net
    command: redis-server --appendonly yes

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    networks:
      - ecom-net
    depends_on:
      - redis-server

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databases/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    networks:
      - ecom-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - "8086:8080"
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: mysql
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: rootpassword
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME: localhost
    command: start-dev
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecom-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.4
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      discovery.type: single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - ecom-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fs 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:9.4.4
  #   container_name: logstash
  #   restart: always
  #   volumes:
  #     - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   ports:
  #     - "5044:5044"
  #     - "5000:5000/tcp"
  #     - "5000:5000/udp"
  #   environment:
  #     LS_JAVA_OPTS: "-Xms256m -Xmx256m"
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   networks:
  #     - ecom-net

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:9.4.4
  #   container_name: kibana
  #   restart: always
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   networks:
  #     - ecom-net

volumes:
  redis_insight_data:
  redis_data:
  mysql_data:
  elasticsearch_data:

networks:
  ecom-net:
    driver: bridge
